/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test-route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RepositoryRouteImport } from './routes/repository'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebookNotebookIdRouteImport } from './routes/notebook.$notebookId'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test-route',
  path: '/test-route',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookNotebookIdRoute = NotebookNotebookIdRouteImport.update({
  id: '/notebook/$notebookId',
  path: '/notebook/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/repository': typeof RepositoryRoute
  '/sign-in': typeof SignInRoute
  '/test-route': typeof TestRouteRoute
  '/notebook/$notebookId': typeof NotebookNotebookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/repository': typeof RepositoryRoute
  '/sign-in': typeof SignInRoute
  '/test-route': typeof TestRouteRoute
  '/notebook/$notebookId': typeof NotebookNotebookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/repository': typeof RepositoryRoute
  '/sign-in': typeof SignInRoute
  '/test-route': typeof TestRouteRoute
  '/notebook/$notebookId': typeof NotebookNotebookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/repository'
    | '/sign-in'
    | '/test-route'
    | '/notebook/$notebookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/repository'
    | '/sign-in'
    | '/test-route'
    | '/notebook/$notebookId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/repository'
    | '/sign-in'
    | '/test-route'
    | '/notebook/$notebookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RepositoryRoute: typeof RepositoryRoute
  SignInRoute: typeof SignInRoute
  TestRouteRoute: typeof TestRouteRoute
  NotebookNotebookIdRoute: typeof NotebookNotebookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-route': {
      id: '/test-route'
      path: '/test-route'
      fullPath: '/test-route'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$notebookId': {
      id: '/notebook/$notebookId'
      path: '/notebook/$notebookId'
      fullPath: '/notebook/$notebookId'
      preLoaderRoute: typeof NotebookNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RepositoryRoute: RepositoryRoute,
  SignInRoute: SignInRoute,
  TestRouteRoute: TestRouteRoute,
  NotebookNotebookIdRoute: NotebookNotebookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
